name = "ChessVision"

[scene]
OUTPUT_DIR = './images/'
RES_X = 512
RES_Y = 512
FILE_TYPE = 'JPEG'
side_length = 0.106768
z_board = 0.0009

[data]
DATA_DIR = './data/'
MOVE_FILE = './temp/moves.json'

[constants]
EMPTY_DELIMITER = 'x'
CHESS_BOARD_LEN = 8
[constants.fen_pieces]
	x = 0
	P = 1
	N = 2
	B = 3
	R = 4
	Q = 5
	K = 6
	p = 7
	n = 8
	b = 9
	r = 10
	q = 11
	k = 12
