name = "ChessVision"

[scene]
OUTPUT_DIR = './images/'
RES_X = 512
RES_Y = 512
FILE_TYPE = 'JPEG'
3d_objects = ['B0','B1','N0','N1','K','Q','R0','R1','P0','P1','P2','P3','P4','P5','P6','P7',
	'b0','b1','n0','n1','k','q','r0','r1','p0','p1','p2','p3','p4','p5','p6','p7',]
side_length = 0.106768
[data]
DATA_DIR = './data/'

[constants]
EMPTY_DELIMITER = 'x'
CHESS_BOARD_LEN = 8
[constants.fen_pieces]
	x = 0
	P = 1
	N = 2
	B = 3
	R = 4
	Q = 5
	K = 6
	p = 7
	n = 8
	b = 9
	r = 10
	q = 11
	k = 12
