name = "ChessVision"

[scene]
OUTPUT_DIR = './images/'
FILE_TYPE = 'JPEG'
RES_X = 512
RES_Y = 512
side_length = 0.106768
z_board = 0.0009
boxes_x = 30
boxes_y = {P = 40, Q = 70, K = 70, N = 60, B = 60, R = 50, p = 40, q = 70, k = 70, n = 60, b = 60, r = 50}

[data]
DATASET = './data/Dec18.pgn'
MOVE_FILE = './data/move.json'
LABEL_FILE = './data/labels_all.json'
FEN_FILE = './data/fen_all.json'
BB_FILE = './data/bb_all.json'
GRID_FILE = './data/grid_all.json'
BoBo_FILE = './data/bounding_boxes_all.json'
MAX_BOARDS = 230000

[constants]
CHESS_BOARD_LEN = 8
EMPTY_DELIMITER = 'x'
fen_pieces = {x = 0, P = 1, N = 2, B = 3, R = 4, Q = 5, K = 6, p = 7, n = 8, b = 9, r = 10, q = 11, k = 12}
