name = "Baselines"

[files]
train_images = ""
test_images = ""
train_labels = ""
test_labels = ""

[constants]
CHESS_BOARD_LEN = 8
EMPTY = 'x'
fen_pieces = {x = 0, P = 1, N = 2, B = 3, R = 4, Q = 5, K = 6, p = 7, n = 8, b = 9, r = 10, q = 11, k = 12}

[models]
[resnet]
name = "resnet100"
[yolo]
name = "yolov5"
